import * as z from "zod";
import { MIRStatus, MIRReportType, MIRClassification } from "@prisma/client";

/* ------------------------------------------------------------------ */
/* Options and Presets                                                */
/* ------------------------------------------------------------------ */

export const STATUS_LABEL: Record<string, string> = {
  DRAFT: "Draft",
  IN_REVIEW: "In Review",
  SUBMITTED: "Submitted",
  CANCELLED: "Cancelled",
};

export const REPORT_TYPE_OPTIONS = [
  { value: "INITIAL", label: "Initial Report" },
  { value: "FOLLOW_UP", label: "Follow-Up Report" },
  { value: "COMBINED", label: "Combined Initial & Final" },
  { value: "FINAL", label: "Final (Reportable Incident)" },
  { value: "FINAL_NON_REPORTABLE", label: "Final (Non-Reportable Incident)" },
];

export const CLASSIFICATION_OPTIONS = [
  { value: "SERIOUS_PUBLIC_HEALTH_THREAT", label: "Serious Public Health Threat" },
  { value: "DEATH", label: "Death" },
  { value: "UNANTICIPATED_DETERIORATION", label: "Unanticipated Serious Deterioration in State of Health" },
  { value: "ALL_OTHER_REPORTABLE", label: "All Other Reportable Incidents" },
];

export const AUTHORITY_PRESETS = [
  "ANSM (France)",
  "BfArM (Germany)",
  "MHRA (United Kingdom)",
  "HPRA (Ireland)",
  "AEMPS (Spain)",
  "Swissmedic (Switzerland)",
  "FAMHP / AFMPS (Belgium)",
  "INFARMED (Portugal)",
  "Ministero della Salute (Italy)",
  "IGJ (Netherlands)",
  "BASG / AGES (Austria)",
  "Läkemedelsverket (Sweden)",
  "Fimea (Finland)",
  "DKMA / Lægemiddelstyrelsen (Denmark)",
  "NoMA (Norway)",
  "US FDA CDRH (21 CFR 803)",
  "Health Canada",
  "TGA (Australia)",
  "EUDAMED Central Portal",
];

export const SUBMISSION_METHODS = [
  "EUDAMED Electronic XML",
  "National Authority Web Portal",
  "Electronic Mail / Signed PDF",
  "API / Machine-to-Machine",
  "Courier / Physical Filing",
];

export const DEVICE_RELATEDNESS_OPTIONS = [
  { value: "CONFIRMED", label: "Confirmed Device Related" },
  { value: "PROBABLE", label: "Probable" },
  { value: "POSSIBLE", label: "Possible" },
  { value: "UNLIKELY", label: "Unlikely" },
  { value: "NOT_RELATED", label: "Not Related" },
  { value: "UNDER_EVALUATION", label: "Under Evaluation" },
];

export const CAUSALITY_OPTIONS = [
  { value: "CAUSAL", label: "Direct Causality Established" },
  { value: "CONTRIBUTORY", label: "Device Contributed to Incident" },
  { value: "COINCIDENTAL", label: "Coincidental / Unrelated Condition" },
  { value: "INCONCLUSIVE", label: "Inconclusive / Pending Investigation" },
];

export const SERIOUSNESS_OPTIONS = [
  { value: "DEATH", label: "Death of a Patient or User" },
  { value: "SERIOUS_DETERIORATION", label: "Serious Deterioration in State of Health" },
  { value: "PUBLIC_HEALTH_THREAT", label: "Serious Public Health Threat" },
  { value: "NEAR_INCIDENT", label: "Potential Serious Incident (Near Incident)" },
  { value: "NON_SERIOUS", label: "Non-Serious" },
];

export const RISK_ASSESSMENT_OPTIONS = [
  { value: "CRITICAL", label: "Critical (Unacceptable Risk)" },
  { value: "HIGH", label: "High Risk" },
  { value: "MEDIUM", label: "Medium / ALARP" },
  { value: "LOW", label: "Low / Acceptable" },
];

/* ------------------------------------------------------------------ */
/* Canonical MIR Zod Schema (EU MIR v7.3.1 Sections 1-5)             */
/* ------------------------------------------------------------------ */

export const mirAttachmentSchema = z.object({
  id: z.string().optional(),
  fileUrl: z.string(),
  fileName: z.string(),
  fileSize: z.number().nullable().optional(),
  mimeType: z.string().nullable().optional(),
});

export const mirSchema = z.object({
  status: z.nativeEnum(MIRStatus),
  reportType: z.string().optional().nullable(),
  mirNumber: z.string().optional().nullable(),

  // =============================================================
  // SECTION 1: ADMINISTRATIVE INFORMATION
  // =============================================================
  ncaName: z.string().optional().nullable(),
  ncaEudamedNum: z.string().optional().nullable(),
  ncaReportNo: z.string().optional().nullable(),
  refNumEudamed: z.string().optional().nullable(),
  reportDate: z.union([z.date(), z.string()]).optional().nullable(),
  adverseEventDateFrom: z.union([z.date(), z.string()]).optional().nullable(),
  adverseEventDateTo: z.union([z.date(), z.string()]).optional().nullable(),
  mfrAwarenessDate: z.union([z.date(), z.string()]).optional().nullable(),
  mfrAwarenessReportDate: z.union([z.date(), z.string()]).optional().nullable(),
  reportNextDate: z.union([z.date(), z.string()]).optional().nullable(),
  expectedDayOfNextReport: z.union([z.date(), z.string()]).optional().nullable(),
  eventClassification: z.string().optional().nullable(),
  statusReporter: z.string().optional().nullable(),
  reporterOtherText: z.string().optional().nullable(),
  authorizedRepresentativeContact: z.string().optional().nullable(),
  arContact: z.string().optional().nullable(),
  submitterContact: z.string().optional().nullable(),
  mfrRef: z.string().optional().nullable(),
  ncaRefMultiDev: z.string().optional().nullable(),
  eudamedRefMultiDev: z.string().optional().nullable(),
  mfrRefMultiDev: z.string().optional().nullable(),
  ncaRefFSCA: z.string().optional().nullable(),
  eudamedRefFSCA: z.string().optional().nullable(),
  mfrRefFSCA: z.string().optional().nullable(),
  psrId: z.string().optional().nullable(),
  pmcfpmpfQuestion: z.boolean().optional().nullable(),
  pmcfpmpfId: z.string().optional().nullable(),

  // Manufacturer information (1.3.2)
  mfrName: z.string().optional().nullable(),
  mfrSRN: z.string().optional().nullable(),
  mfrContactPersonFirstName: z.string().optional().nullable(),
  mfrContactPersonSecondName: z.string().optional().nullable(),
  mfrEmailAddress: z.string().optional().nullable(),
  mfrPhone: z.string().optional().nullable(),
  mfrCountry: z.string().optional().nullable(),
  mfrOrgStreet: z.string().optional().nullable(),
  mfrOrgStreetNum: z.string().optional().nullable(),
  mfrAddress: z.string().optional().nullable(),
  mfrOrgPOBox: z.string().optional().nullable(),
  mfrCity: z.string().optional().nullable(),
  mfrPostcode: z.string().optional().nullable(),

  // Authorized representative (1.3.3)
  arName: z.string().optional().nullable(),
  arSRN: z.string().optional().nullable(),
  arContactPersonFirstName: z.string().optional().nullable(),
  arContactPersonSecondName: z.string().optional().nullable(),
  arEmailAddress: z.string().optional().nullable(),
  arPhone: z.string().optional().nullable(),
  arCountry: z.string().optional().nullable(),
  arStreet: z.string().optional().nullable(),
  arStreetNum: z.string().optional().nullable(),
  arAddress: z.string().optional().nullable(),
  arPOBox: z.string().optional().nullable(),
  arCity: z.string().optional().nullable(),
  arPostcode: z.string().optional().nullable(),

  // Submitter details if not manufacturer or AR (1.3.4)
  reporterOrgName: z.string().optional().nullable(),
  reporterContactPersonFirstName: z.string().optional().nullable(),
  reporterContactPersonSecondName: z.string().optional().nullable(),
  reporterOrgEmailAddress: z.string().optional().nullable(),
  reporterOrgPhone: z.string().optional().nullable(),
  reporterOrgCountry: z.string().optional().nullable(),
  reporterOrgStreet: z.string().optional().nullable(),
  reporterOrgStreetNum: z.string().optional().nullable(),
  reporterOrgAddress: z.string().optional().nullable(),
  reporterOrgPOBox: z.string().optional().nullable(),
  reporterOrgCity: z.string().optional().nullable(),
  reporterOrgPostcode: z.string().optional().nullable(),

  // =============================================================
  // SECTION 2: MEDICAL DEVICE INFORMATION
  // =============================================================
  udiDI: z.string().optional().nullable(),
  udiDIEntity: z.string().optional().nullable(),
  udiPI: z.string().optional().nullable(),
  udiDIBasic: z.string().optional().nullable(),
  basicEntity: z.string().optional().nullable(),
  udiDIUnitUse: z.string().optional().nullable(),
  unitOfUseEntity: z.string().optional().nullable(),
  nomenclatureSystem: z.string().optional().nullable(),
  nomenclatureSystemOther: z.string().optional().nullable(),
  nomenclatureCode: z.string().optional().nullable(),
  brandName: z.string().optional().nullable(),
  deviceDescription: z.string().optional().nullable(),
  deviceNomenclature: z.string().optional().nullable(),
  modelNum: z.string().optional().nullable(),
  catalogNum: z.string().optional().nullable(),
  serialNum: z.string().optional().nullable(),
  batchNum: z.string().optional().nullable(),
  deviceSoftwareVer: z.string().optional().nullable(),
  deviceFirmwareVer: z.string().optional().nullable(),
  deviceMfrDate: z.union([z.date(), z.string()]).optional().nullable(),
  dateLotReleased: z.union([z.date(), z.string()]).optional().nullable(),
  deviceExpiryDate: z.union([z.date(), z.string()]).optional().nullable(),
  expiryDate: z.union([z.date(), z.string()]).optional().nullable(),
  implantedDateFrom: z.union([z.date(), z.string()]).optional().nullable(),
  dateOfImplantFrom: z.union([z.date(), z.string()]).optional().nullable(),
  implantedDateTo: z.union([z.date(), z.string()]).optional().nullable(),
  dateOfImplantTo: z.union([z.date(), z.string()]).optional().nullable(),
  explantedDateFrom: z.union([z.date(), z.string()]).optional().nullable(),
  dateOfExplantFrom: z.union([z.date(), z.string()]).optional().nullable(),
  explantedDateTo: z.union([z.date(), z.string()]).optional().nullable(),
  dateOfExplantTo: z.union([z.date(), z.string()]).optional().nullable(),
  numYears: z.number().optional().nullable(),
  numMonths: z.number().optional().nullable(),
  numDays: z.number().optional().nullable(),
  implantDuration: z.union([z.string(), z.number()]).optional().nullable(),
  implantFacilityName: z.string().optional().nullable(),
  implantFacitlityName: z.string().optional().nullable(),
  explantFacilityName: z.string().optional().nullable(),
  nbIdNum: z.string().optional().nullable(),
  nbIdNum2: z.string().optional().nullable(),
  notifiedBodyId: z.string().optional().nullable(),
  nbCertNum: z.string().optional().nullable(),
  nbCertNum2: z.string().optional().nullable(),
  notifiedBodyCerNoOfDevice: z.string().optional().nullable(),
  notifiedBodyCertNo: z.string().optional().nullable(),
  deviceMarketDateType: z.string().optional().nullable(),
  deviceMarketDate: z.union([z.date(), z.string()]).optional().nullable(),
  appLegislationUnknown: z.boolean().optional().nullable(),
  deviceClass: z.boolean().optional().nullable(),
  devicePlacedMarket: z.boolean().optional().nullable(),
  devicePlacedOnMarket: z.union([z.boolean(), z.string()]).optional().nullable(),
  deviceClassMDD: z.string().optional().nullable(),
  mddClass: z.string().optional().nullable(),
  deviceClassIVDD: z.string().optional().nullable(),
  ivddClass: z.string().optional().nullable(),
  deviceClassMDR: z.string().optional().nullable(),
  mdrClass: z.string().optional().nullable(),
  deviceClassIVDR: z.string().optional().nullable(),
  ivdrClass: z.string().optional().nullable(),
  deviceClassMDRType: z.any().optional().nullable(),
  deviceClassIVDRType: z.any().optional().nullable(),
  deviceFulfill: z.boolean().optional().nullable(),
  competentAuthName: z.string().optional().nullable(),
  relevantName: z.string().optional().nullable(),
  distributionEEA: z.boolean().optional().nullable(),
  distributionAll: z.boolean().optional().nullable(),
  marketDistributionOfDevice: z.string().optional().nullable(),
  otherCountries: z.string().optional().nullable(),
  countriesDistributedTo: z.string().optional().nullable(),
  deviceAccessories: z.string().optional().nullable(),
  relevantAccessories: z.string().optional().nullable(),
  deviceAssociated: z.string().optional().nullable(),
  relevantAssociatedDevices: z.string().optional().nullable(),

  // =============================================================
  // SECTION 3: INCIDENT INFORMATION (INITIAL REPORTER)
  // =============================================================
  eventDescription: z.string().optional().nullable(),
  imdrfProblemCodes: z.any().optional().nullable(),
  imdrfA: z.any().optional().nullable(),
  imdrfCodeMissing: z.string().optional().nullable(),
  numPatientsInvolved: z.number().optional().nullable(),
  currentDeviceLocation: z.string().optional().nullable(),
  currentDeviceLocationOtherText: z.string().optional().nullable(),
  deviceOperatorAtEvent: z.string().optional().nullable(),
  deviceOperatorAtEventOther: z.string().optional().nullable(),
  deviceUsage: z.string().optional().nullable(),
  deviceUsageOther: z.string().optional().nullable(),
  patientRemedialAction: z.string().optional().nullable(),
  patientStatusIntervention: z.string().optional().nullable(),
  patientStatus: z.string().optional().nullable(),
  patientIntervention: z.string().optional().nullable(),
  imdrfClinicalCodes: z.any().optional().nullable(),
  imdrfHealthCodes: z.any().optional().nullable(),
  imdrf3: z.any().optional().nullable(),
  imdrfE: z.any().optional().nullable(),
  imdrfF: z.any().optional().nullable(),
  imdrfMissingCodeHealthEffect: z.string().optional().nullable(),
  patientAgeYears: z.number().optional().nullable(),
  patientAgeMonths: z.number().optional().nullable(),
  patientAgeDays: z.number().optional().nullable(),
  gender: z.string().optional().nullable(),
  massKG: z.number().optional().nullable(),
  heightCM: z.number().optional().nullable(),
  patientPriorMedication: z.string().optional().nullable(),
  initialReporterRole: z.string().optional().nullable(),
  initialReporterRoleOther: z.string().optional().nullable(),
  healthcareFacilityName: z.string().optional().nullable(),
  healthcareFacilityRepNum: z.string().optional().nullable(),
  healthcareFacilityContactFirstName: z.string().optional().nullable(),
  healthcareFacilityContactLastName: z.string().optional().nullable(),
  healthcareFacilityEmail: z.string().optional().nullable(),
  healthcareFacilityPhone: z.string().optional().nullable(),
  healthcareFacilityCountry: z.string().optional().nullable(),
  healthcareFacilityCountryOther: z.string().optional().nullable(),
  healthcareFacilityStreet: z.string().optional().nullable(),
  healthcareFacilityStreetNum: z.string().optional().nullable(),
  healthcareFacilityAddress: z.string().optional().nullable(),
  healthcareFacilityPOBox: z.string().optional().nullable(),
  healthcareFacilityCity: z.string().optional().nullable(),
  healthcareFacilityPostcode: z.string().optional().nullable(),

  // =============================================================
  // SECTION 4: MANUFACTURER ANALYSIS & CAUSE INVESTIGATION
  // =============================================================
  manufacturersPrelimAnalysis: z.string().optional().nullable(),
  suspicionRelationship: z.boolean().optional().nullable(),
  manufacturersInitialCorrecAction: z.string().optional().nullable(),
  initialManufacturerCapa: z.string().optional().nullable(),
  furtherInvestigations: z.string().optional().nullable(),
  rootCauses: z.string().optional().nullable(),
  manufacturersWhyNotReportable: z.string().optional().nullable(),
  reasonForNotReportable: z.string().optional().nullable(),
  rootCauseConfirmed: z.boolean().optional().nullable(),
  relationshipIncidentSubstance: z.string().optional().nullable(),
  riskAssReviewed: z.boolean().optional().nullable(),
  rationaleNoReview: z.string().optional().nullable(),
  riskAssAdequate: z.boolean().optional().nullable(),
  riskAssResults: z.string().optional().nullable(),
  imdrfTypeInvestigationCodes: z.any().optional().nullable(),
  imdrfInvestigationFindingsCodes: z.any().optional().nullable(),
  imdrfInvestigationConclusionCodes: z.any().optional().nullable(),
  imdrfMissingCodeCauseInvestigation: z.string().optional().nullable(),
  imdrfComponentCodes: z.any().optional().nullable(),
  imdrfG: z.any().optional().nullable(),
  imdrfMissingComponentCodes: z.string().optional().nullable(),
  correctiveAction: z.string().optional().nullable(),
  anyActionTaken: z.string().optional().nullable(),
  correctiveActionSchedule: z.string().optional().nullable(),
  actionImplementationSchedule: z.string().optional().nullable(),
  manufacturersFinalComments: z.string().optional().nullable(),
  finalManufacturerComments: z.string().optional().nullable(),
  similarIncImdrfCodesAnnexA: z.any().optional().nullable(),
  similarIncImdrfCodesAnnexC: z.any().optional().nullable(),
  similarIncOtherReportingCodes: z.string().optional().nullable(),
  similarIncOtherReportingCodesText: z.string().optional().nullable(),
  similarIncInHouseCodes: z.any().optional().nullable(),
  similarVariant: z.string().optional().nullable(),
  similarVariantDetails: z.string().optional().nullable(),
  numberBasedOn: z.string().optional().nullable(),
  numberBasedOnOther: z.string().optional().nullable(),
  similarIncidentsHistory: z.any().optional().nullable(),
  howWereDetermined: z.string().optional().nullable(),

  // =============================================================
  // SECTION 5: GENERAL COMMENTS & SIGN-OFF
  // =============================================================
  additionalComments: z.string().optional().nullable(),
  businessComments: z.string().optional().nullable(),
  lateReason: z.string().optional().nullable(),
  cidCapaForLateReportable: z.string().optional().nullable(),
  cidCapaLateReportable: z.string().optional().nullable(),
  commentsForLateReportable: z.string().optional().nullable(),
  processStageForLateReportable: z.string().optional().nullable(),
  attachment: z.any().optional().nullable(),
  attachments: z.array(mirAttachmentSchema).optional().nullable(),
  sCreateTimeStamp: z.union([z.date(), z.string()]).optional().nullable(),
  preparedById: z.string().optional().nullable(),
  reviewedById: z.string().optional().nullable(),
  approvedById: z.string().optional().nullable(),

  // Legacy / Form Compatibility Fields
  manufacturerReference: z.string().optional().nullable(),
  previousMirReference: z.string().optional().nullable(),
  competentAuthority: z.string().optional().nullable(),
  competentAuthorityReference: z.string().optional().nullable(),
  submissionCountry: z.string().optional().nullable(),
  submissionMethod: z.string().optional().nullable(),
  submittedBy: z.string().optional().nullable(),
  submissionDate: z.date().optional().nullable(),
  dueDate: z.date().optional().nullable(),
  initialDeviceRelatedness: z.string().optional().nullable(),
  initialCausalityAssessment: z.string().optional().nullable(),
  initialSeriousnessAssessment: z.string().optional().nullable(),
  initialRiskAssessment: z.string().optional().nullable(),
  preliminaryConclusion: z.string().optional().nullable(),
  investigationStarted: z.boolean().optional(),
  investigationStartDate: z.date().optional().nullable(),
  finalDeviceRelatedness: z.string().optional().nullable(),
  finalCausalityAssessment: z.string().optional().nullable(),
  finalCausalityRationale: z.string().optional().nullable(),
  manufacturerConclusion: z.string().optional().nullable(),
  incidentConfirmed: z.boolean().optional(),
  deviceContributionConfirmed: z.boolean().optional(),
  recurrencePotential: z.string().optional().nullable(),
  finalRiskAssessmentSummary: z.string().optional().nullable(),
  manufacturerFinalStatement: z.string().optional().nullable(),
});

export type MIRFormValues = z.infer<typeof mirSchema>;
